# Generated by Django 3.0.2 on 2020-01-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20200116_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm_logs',
            name='Alarm_test2',
        ),
        migrations.RemoveField(
            model_name='alarms',
            name='Alarm_test2',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='Alarm_test2',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='Alarm_test2',
        ),
    ]
