# Generated by Django 2.2.6 on 2019-12-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='LastOrder',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='LastOrderTime',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
