# Generated by Django 3.0.2 on 2020-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm_logs',
            name='Alarm_test2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarms',
            name='Alarm_test2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='Alarm_test2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='Alarm_test2',
            field=models.IntegerField(null=True),
        ),
    ]
